name: post

on:
  # schedule:
  #   - cron: "30 14 * * *"
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: .github/workflows/
jobs:
  build:
    name: post
    runs-on: ubuntu-latest
    steps:
      # - name: ls
      #   run: ls -l
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: ./.github/workflows/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Create Sitemap
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{secrets.SUPABASE_SERVICE_ROLE_KEY}}
        run: npm run post $SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY